#!/bin/sh
if ! npx commitlint --edit "$1"; then
  echo "
📘Formato correto:
<tipo>(escopo opcional): <descrição em minúsculas>

Tipos aceitos:
  feat     -> nova funcionalidade
  fix      -> correção de bug
  docs     -> apenas documentação
  style    -> formatação (semântico)
  refactor -> refatoração
  test     -> testes
  chore    -> manutenção/configuração

Exemplo válido:
  feat(auth): adiciona autenticação jwt
"
  exit 1
fi
